### ISSUE TITLE
Doxycycline

### ISSUE THREAD

**Issue by dryphi** [aetherist/antibiogram#2]
Two issues noted related to doxycycline in the antibiogram:
1. it is misspelled. The correct spelling is shown here. In the file it is spelled "Doxyclycine".
2. I believe doxy covers MSSA and MRSA unless there's recent data to the contrary.

**Comment by aetherist** [comment]
Sorry for the delay, I just finished residency and had completely forgotten about this project until recently. Thank you for finding the typo! I have fixed it. As for doxy - it is so variable in coverage that I left it out. At my hospital, it covers only a small fraction of the cases. As this is primarily targeted to learners, if there is a Uworld/Step question that assumes this coverage, I'll change it, but I haven't encountered that yet.
