### ISSUE TITLE
Atypicals

### ISSUE THREAD

**Issue by AristoSocrates** [aetherist/antibiogram#3]
Hi there,

Thank you so much for this antibiogram - I've found it very useful to help me during residency. 

As feedback, I think it would be good to briefly outline which organisms count under 'atypicals' (e.g. 'Mycoplasma') so it's more accessible if it's printed or made into a poster form (e.g. in a hospital doctor's mess). 

It's not necessary at all but would be useful as a teaching resource for medical students.

**Comment by aetherist** [comment]
Sorry for the delay, I just finished residency and had completely forgotten about this project until recently. So glad that it was helpful to you! I changed the image to include mycoplasma as an example. I wish there was more space to include other examples, but I've tried to keep it as simple as possible!
